# Generated by Django 5.2.15 on 2026-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_turnaround_hrs', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
